.Dd December 13, 2024
.Dt LIBHTTPC_METHOD 3
.Os
.
.Sh NAME
.Nm LibHTTPC_Method
.Nd HTTP method
.
.Sh DESCRIPTION
HTTP/1.1
comes with
some methods.
.Xr libhttpc 3
provides
enum
and QoL functions
for using them.
.Ss Methods
These are methods
that are supported
by
.Xr libhttpc 3 :
.Bl -tag
.It Dv LibHTTPC_Method_OPTIONS
OPTIONS
.It Dv LibHTTPC_Method_GET
GET
.It Dv LibHTTPC_Method_HEAD
HEAD
.It Dv LibHTTPC_Method_POST
POST
.It Dv LibHTTPC_Method_PUT
PUT
.It Dv LibHTTPC_Method_DELETE
DELETE
.It Dv LibHTTPC_Method_TRACE
TRACE
.It Dv LibHTTPC_Method_CONNECT
CONNECT
.El
Also,
there's
.Dv LibHTTPC_Method_EXTENSION_METHOD
for user-defined methods.
.
.Sh SEE ALSO
.Xr libhttpc 3 ,
.Xr libhttpc_dumpmethod 3 ,
.Xr libhttpc_loadmethod 3
.
.Sh AUTHORS
.An Nakidai Perumenei Aq Mt nakidai@disroot.org
