.Dd December 13, 2024
.Dt LIBHTTPC_HEADER 3
.Os
.
.Sh NAME
.Nm LibHTTPC_Header
.Nd HTTP header structure
.
.Sh DESCRIPTION
HTTP/1.1
comes with
some headers.
.Xr libhttpc 3
provides
enum
and QoL functions
for using them.
.
.Pp
Library declare
.Nm
as follows:
.Bd -literal -offset indent
struct LibHTTPC_Header
{
    const char *name;
    const char *value;
};
.Ed
.
.Sh SEE ALSO
.Xr libhttpc 3 ,
.Xr libhttpc_headertype 3 ,
.Xr libhttpc_dumpheader 3 ,
.Xr libhttpc_loadheader 3
.
.Sh AUTHORS
.An Nakidai Perumenei Aq Mt nakidai@disroot.org
