.Dd December 14, 2024
.Dt LIBHTTPC_DUMPSTATUS 3
.Os
.
.Nm LibHTTPC_dumpStatus
.Nd convert
.Xr libhttpc_status 3
to string
.
.Sh SYNOPSIS
.In libhttpc/libhttpc.h
.Ft "const char *"
.Fn LibHTTPC_dumpStatus "enum LibHTTPC_Status status"
.
.Sh DESCRIPTION
.Fn LibHTTPC_dumpStatus
returns
usually used
phrase
for given
.Xr libhttpc_status 3 .
.
.Sh SEE ALSO
.Xr libhttpc 3 ,
.Xr libhttpc_status 3
.
.Sh AUTHORS
.An Nakidai Perumenei Aq Mt nakidai@disroot.org
