.Dd December 13, 2024
.Dt LIBHTTPC_RESPONSE 3
.Os
.
.Sh NAME
.Nm LibHTTPC_Response
.Nd how
.Xr libhttpc 3
stores HTTP responses
.
.Sh DESCRIPTION
.Xr libhttpc 3
stores responses
as follows:
.Bd -literal -offset indent
struct LibHTTPC_Response
{
    char                   *buf;
    const char             *version;
    enum LibHTTPC_Status    status;
    const char             *phrase;
    struct LibHTTPC_Header *headers;
    const char             *body;
    size_t                  header_count;
};
.Ed
Let's see
what means
each member:
.Bl -tag
.It char *buf
Pointer to
the buffer
where response
is stored.
Presented
only for consistence,
doesn't mean anything
for the library.
.It const char *version
Pointer to
the HTTP version number
.It enum LibHTTPC_Status status
Response code
.It const char *phrase
Explanation
of response code
.It struct LibHTTPC_Header *headers
Array of headers
.It const char *body
Pointer to
the entity
.It size_t header_count
Length of
.Ql header_count
array
.
.Sh SEE ALSO
.Xr libhttpc 3 ,
.Xr libhttpc_dumpresponse 3 ,
.Xr libhttpc_header 3 ,
.Xr libhttpc_status 3
.Xr libhttpc_writeresponse 3
.
.Sh AUTHORS
.An Nakidai Perumenei Aq Mt nakidai@disroot.org
