.Dd December 14, 2024
.Dt LIBHTTPC_DUMPMETHOD 3
.Os
.
.Sh NAME
.Nm LibHTTPC_dumpMethod
.Nd convert
.Xr libhttpc_method 3
to string
.
.Sh SYNOPSIS
.In libhttpc/libhttpc.h
.Ft "const char *"
.Fn LibHTTPC_dumpMethod "enum LibHTTPC_Method header"
.
.Sh DESCRIPTION
.Fn LibHTTPC_dumpMethod
converts
.Ft enum LibHTTPC_Method
to
.Ft const char * .
To view
all available methods,
read
.Xr libhttpc_method 3 .
.
.Sh SEE ALSO
.Xr libhttpc 3 ,
.Xr libhttpc_method 3
.
.Sh AUTHORS
.An Nakidai Perumenei Aq Mt nakidai@disroot.org
