.Dd December 15, 2024
.Dt TODO 7
.Os
.
.Sh NAME
.Nm TODO
.Nd some things
that I want to do
with this library
.
.Sh DESCRIPTION
.Bl -bullet
.It
Implement handler.
It should be a function
that calls other ones
depending on the
.Xr uri 7 .
.It
Implement behavior
for
.Xr libhttpc_readrequest 3
when
.Fa buf
is
.Dv NULL .
.It
Implement something kinda
.Xr errno 3
for
.Xr libhttpc 3
.El
.
.Sh AUTHORS
.An Nakidai Perumenei Aq Mt nakidai@disroot.org
