.Dd December 14, 2024
.Dt TODO 7
.Os
.
.Sh NAME
.Nm TODO
.Nd some things
that I want to do
with this library
.
.Sh DESCRIPTION
.Bl -bullet
.It
Implement
.Fn LibHTTPC_readRequest .
It should be able to
parse requests
from
.Xr socket 2
directly.
.It
Make
.Fn LibHTTPC_dumpResponse
accept
.Dv NULL
in
.Fa buf .
In this way
function should
allocate buffer itself.
.El
.
.Sh AUTHORS
.An Nakidai Perumenei Aq Mt nakidai@disroot.org
